# Generated by Django 3.2 on 2023-05-27 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Exam', max_length=255, verbose_name='Exam Title')),
                ('numberOfQuestions', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('time', models.PositiveIntegerField(help_text='duration of the exam')),
                ('scoreToPass', models.PositiveIntegerField()),
                ('exam_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_level_section', to='account.levelsection')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_level', to='account.level')),
                ('subject', models.ForeignKey(default='Subject not selected', on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_material.quiz')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('technique', models.IntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Type of Question')),
                ('title', models.CharField(max_length=255, verbose_name='Question')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_material.quiz', verbose_name='Exam name')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Answer')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_material.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
    ]
